# Generated by Django 5.2.17 on 2026-09-21 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('instructor', models.CharField(max_length=100)),
                ('capacidad_maxima', models.IntegerField()),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('duracion_dias', models.IntegerField(default=30)),
            ],
            options={
                'ordering': ['precio'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gimnasio.plan')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=20)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gimnasio.clase')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gimnasio.socio')),
            ],
            options={
                'ordering': ['-fecha_inscripcion'],
            },
        ),
    ]
