--
-- PostgreSQL database dump
--

\restrict DOhknbYAOA6idNE1E6BlbgSfrHlS3PQLSSMQy2uphIu419GoaGVbo52fxfoHTXz

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Gimnasio_clase; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Gimnasio_clase" (
    id bigint NOT NULL,
    nombre character varying(50) NOT NULL,
    instructor character varying(100) NOT NULL,
    capacidad_maxima integer NOT NULL
);


--
-- Name: Gimnasio_clase_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Gimnasio_clase" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Gimnasio_clase_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Gimnasio_inscripcion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Gimnasio_inscripcion" (
    id bigint NOT NULL,
    fecha_inscripcion date NOT NULL,
    estado character varying(20) NOT NULL,
    clase_id bigint NOT NULL,
    socio_id bigint NOT NULL
);


--
-- Name: Gimnasio_inscripcion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Gimnasio_inscripcion" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Gimnasio_inscripcion_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Gimnasio_plan; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Gimnasio_plan" (
    id bigint NOT NULL,
    nombre character varying(50) NOT NULL,
    precio integer NOT NULL,
    duracion_dias integer NOT NULL
);


--
-- Name: Gimnasio_plan_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Gimnasio_plan" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Gimnasio_plan_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Gimnasio_socio; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Gimnasio_socio" (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    rut character varying(12) NOT NULL,
    email character varying(254) NOT NULL,
    plan_id bigint NOT NULL
);


--
-- Name: Gimnasio_socio_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Gimnasio_socio" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Gimnasio_socio_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Data for Name: Gimnasio_clase; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Gimnasio_clase" (id, nombre, instructor, capacidad_maxima) FROM stdin;
1	Yoga	Ana Torres	20
2	Running	Carlos Rojas	30
3	Pesas	Jorge Muñoz	25
\.


--
-- Data for Name: Gimnasio_inscripcion; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Gimnasio_inscripcion" (id, fecha_inscripcion, estado, clase_id, socio_id) FROM stdin;
5	2026-09-21	FINALIZADA	3	6
4	2026-09-21	FINALIZADA	2	1
3	2026-09-21	FINALIZADA	2	1
1	2026-09-21	FINALIZADA	3	1
7	2026-09-21	ACTIVA	2	11
8	2026-09-21	ACTIVA	1	12
9	2026-09-21	ACTIVA	2	13
10	2026-09-21	ACTIVA	2	14
11	2026-09-21	FINALIZADA	2	15
12	2026-09-21	ACTIVA	2	16
13	2026-09-21	ACTIVA	3	17
14	2026-09-21	ACTIVA	2	18
15	2026-09-21	ACTIVA	1	19
16	2026-09-21	ACTIVA	2	20
17	2026-09-21	ACTIVA	2	21
18	2026-09-21	ACTIVA	2	22
19	2026-09-21	ACTIVA	2	23
20	2026-09-21	ACTIVA	3	24
21	2026-09-21	ACTIVA	3	25
22	2026-09-21	CANCELADA	1	26
23	2026-09-21	ACTIVA	2	27
24	2026-09-21	ACTIVA	2	28
26	2026-09-21	ACTIVA	1	30
27	2026-09-21	ACTIVA	1	31
28	2026-09-21	ACTIVA	3	32
29	2026-09-21	CANCELADA	1	33
30	2026-09-21	ACTIVA	2	34
31	2026-09-21	ACTIVA	3	35
32	2026-09-21	ACTIVA	1	36
33	2026-09-21	ACTIVA	2	37
34	2026-09-21	ACTIVA	1	38
35	2026-09-21	ACTIVA	1	39
36	2026-09-21	ACTIVA	1	40
37	2026-09-21	CANCELADA	2	41
38	2026-09-21	ACTIVA	2	42
39	2026-09-21	ACTIVA	1	43
40	2026-09-21	ACTIVA	3	44
41	2026-09-21	ACTIVA	2	45
42	2026-09-21	CANCELADA	2	46
43	2026-09-21	ACTIVA	1	47
44	2026-09-21	FINALIZADA	2	48
45	2026-09-21	CANCELADA	2	49
46	2026-09-21	ACTIVA	1	50
47	2026-09-21	ACTIVA	1	51
48	2026-09-21	ACTIVA	2	52
49	2026-09-21	ACTIVA	3	53
50	2026-09-21	ACTIVA	1	54
51	2026-09-21	ACTIVA	2	55
52	2026-09-21	FINALIZADA	1	56
53	2026-09-21	ACTIVA	2	57
54	2026-09-21	ACTIVA	2	58
55	2026-09-21	FINALIZADA	2	59
56	2026-09-21	ACTIVA	3	60
57	2026-09-21	ACTIVA	3	61
58	2026-09-21	ACTIVA	2	62
59	2026-09-21	ACTIVA	2	63
60	2026-09-21	ACTIVA	2	64
61	2026-09-21	ACTIVA	3	65
62	2026-09-21	ACTIVA	3	66
63	2026-09-21	ACTIVA	3	67
64	2026-09-21	ACTIVA	2	68
65	2026-09-21	ACTIVA	3	69
25	2026-09-21	CANCELADA	3	29
66	2026-09-21	ACTIVA	2	59
67	2026-09-21	ACTIVA	3	70
68	2026-09-21	ACTIVA	2	71
\.


--
-- Data for Name: Gimnasio_plan; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Gimnasio_plan" (id, nombre, precio, duracion_dias) FROM stdin;
2	Mensual	30000	30
3	Trimestral	80000	90
4	Semestral	150000	180
5	Anual	280000	365
\.


--
-- Data for Name: Gimnasio_socio; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Gimnasio_socio" (id, nombre, rut, email, plan_id) FROM stdin;
1	victor carrasco	12.146.250-8	victor.carrasco.gy@gmail.com	5
4	Detalle Test	22.333.444-5	det@x.cl	2
6	Juan Pérez	12.345.678-9	juan@mail.cl	2
9	mbappe	11794830-3	victor.carrasco.gy@gmail.com	3
12	Matías Vargas Díaz	10116074-1	cliente02.matías@mail.cl	2
13	Martina Salazar Gómez	10134552-8	cliente03.martina@mail.cl	5
14	Belén Rodríguez Medina	10186015-0	cliente04.belén@mail.cl	4
15	Felipe Pizarro Silva	10245133-1	cliente05.felipe@mail.cl	3
16	Hernán Pizarro Contreras	10320350-8	cliente06.hernán@mail.cl	5
17	Sofía Torres Valenzuela	10344466-0	cliente07.sofía@mail.cl	2
18	Florencia Castro Rodríguez	10418895-K	cliente08.florencia@mail.cl	3
22	Quimey Sepúlveda Araya	10630070-2	cliente12.quimey@mail.cl	5
24	Javier Rivera Rodríguez	10722400-1	cliente14.javier@mail.cl	4
25	Quimey Aguilar Muñoz	10798748-8	cliente15.quimey@mail.cl	2
26	Sebastián Vargas Rodríguez	10858335-1	cliente16.sebastián@mail.cl	4
27	Gabriela Rivera Castillo	10896751-8	cliente17.gabriela@mail.cl	5
28	Cristóbal Núñez Muñoz	10932925-8	cliente18.cristóbal@mail.cl	5
29	Patricio Pérez Araya	10995501-4	cliente19.patricio@mail.cl	5
30	Cristóbal Sepúlveda Sepúlveda	11019572-8	cliente20.cristóbal@mail.cl	4
31	Josefa Medina Fuentes	11090033-3	cliente21.josefa@mail.cl	3
32	Hernán Araya Torres	11172872-7	cliente22.hernán@mail.cl	2
33	Olivia Muñoz Soto	11218033-9	cliente23.olivia@mail.cl	2
34	Helena Araya Espinoza	11276342-1	cliente24.helena@mail.cl	4
35	Fernanda Araya Navarro	11366189-9	cliente25.fernanda@mail.cl	4
36	Camila Farias Guzmán	11437687-5	cliente26.camila@mail.cl	2
37	Patricio Fuentes Fuentes	11497160-1	cliente27.patricio@mail.cl	5
38	Patricio Soto Henríquez	11548669-7	cliente28.patricio@mail.cl	5
39	Felipe Araya Rodríguez	11634524-0	cliente29.felipe@mail.cl	4
40	Katherine Pizarro Muñoz	11702089-0	cliente30.katherine@mail.cl	4
42	Álvaro Tapia Pérez	11876000-0	cliente32.álvaro@mail.cl	2
44	Hernán Orellana Araya	12006443-6	cliente34.hernán@mail.cl	5
45	Matías Orellana Núñez	12076391-K	cliente35.matías@mail.cl	3
46	Quimey Álvarez Sepúlveda	12132571-3	cliente36.quimey@mail.cl	3
47	Elisa Campos Orellana	12157079-0	cliente37.elisa@mail.cl	2
48	Emilia Araya Castro	12189440-5	cliente38.emilia@mail.cl	3
49	Damián Gómez Núñez	12244091-9	cliente39.damián@mail.cl	2
50	Quimey Martínez Silva	12272668-2	cliente40.quimey@mail.cl	5
51	Nicolás Maldonado Rivera	12315275-5	cliente41.nicolás@mail.cl	3
52	Paula Vargas Espinoza	12336933-1	cliente42.paula@mail.cl	2
53	Álvaro Henríquez Aguilar	12386268-2	cliente43.álvaro@mail.cl	4
54	Catalina Castro Bustos	12420804-8	cliente44.catalina@mail.cl	5
59	Benjamín Sandoval Fuentes	12629812-3	cliente49.benjamín@mail.cl	4
60	Rodrigo Ortega Álvarez	12681397-5	cliente50.rodrigo@mail.cl	5
61	Matías Flores Díaz	12730634-2	cliente51.matías@mail.cl	2
62	Natalia Ortega Martínez	12786748-6	cliente52.natalia@mail.cl	4
64	Ursula Sandoval Martínez	12917181-9	cliente54.ursula@mail.cl	3
66	Álvaro López Campos	13039629-K	cliente56.álvaro@mail.cl	5
67	Sebastián Hernández Vargas	13054682-4	cliente57.sebastián@mail.cl	5
69	mbappe	12345678-9	juan@sakdja.cl	5
8	mbappe	21811781-3	sadsaa@sadasdsa.cl	2
11	Álvaro Espinoza Araya	10029592-0	cliente01.álvaro@mail.cl	2
19	Paula Rodríguez Mendoza	10443253-9	cliente09.paula@mail.cl	2
20	Tomás Tapia Pérez	10531253-3	cliente10.tomás@mail.cl	2
21	Lorena Salazar Tapia	10554928-3	cliente11.lorena@mail.cl	2
23	Antonia Castro Torres	10701225-9	cliente13.antonia@mail.cl	2
41	Walter Peña Morales	11789934-K	cliente31.walter@mail.cl	2
43	Daniela Ortega Contreras	11960615-2	cliente33.daniela@mail.cl	2
55	Constanza Díaz Gutiérrez	12476208-5	cliente45.constanza@mail.cl	2
56	Bruno Campos Morales	12537565-8	cliente46.bruno@mail.cl	2
57	Álvaro Reyes Farias	12555813-2	cliente47.álvaro@mail.cl	2
58	Catalina Navarro Torres	12584981-6	cliente48.catalina@mail.cl	2
63	Ignacio Mendoza Maldonado	12858902-0	cliente53.ignacio@mail.cl	2
65	Valentina Valenzuela Aguilar	12974934-6	cliente55.valentina@mail.cl	2
68	Nicolás Ortega Navarro	13127636-K	cliente58.nicolás@mail.cl	2
70	victor carrasco	76565555-6	victor.carrasco.gy@gsadsa.cl	3
71	mbappe2	32123223-3	21321321@ewqqew.cl	2
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add clase	7	add_clase
26	Can change clase	7	change_clase
27	Can delete clase	7	delete_clase
28	Can view clase	7	view_clase
29	Can add plan	8	add_plan
30	Can change plan	8	change_plan
31	Can delete plan	8	delete_plan
32	Can view plan	8	view_plan
33	Can add socio	9	add_socio
34	Can change socio	9	change_socio
35	Can delete socio	9	delete_socio
36	Can view socio	9	view_socio
37	Can add inscripcion	10	add_inscripcion
38	Can change inscripcion	10	change_inscripcion
39	Can delete inscripcion	10	delete_inscripcion
40	Can view inscripcion	10	view_inscripcion
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1000000$w8BZsBEG1xfAKsKiU1PTNk$59EjSEm8WrbsoTUUVyFJneG5KeAfojZXiKGvF0gZLH8=	2026-09-21 17:43:55.528063-03	t	Victor			asdjksaj@sadkas.cl	t	t	2026-09-21 15:57:18.451809-03
2	pbkdf2_sha256$1000000$5A1RNyJnRJZfHlojJzZjxj$CPvSRDg50QtDxvGxxYS1MiminrSkpYDxThFLMN2XCzA=	2026-09-21 17:53:14.469293-03	t	admin			admin@x.cl	t	t	2026-09-21 17:21:28.58673-03
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-09-21 16:04:51.080666-03	1	victor carrasco (12.146.250-8)	1	[{"added": {}}]	9	1
2	2026-09-21 16:06:52.316746-03	6	Plan plan 2 meses ($45000)	1	[{"added": {}}]	8	1
3	2026-09-21 16:07:32.532452-03	1	Inscripción: victor carrasco en Pesas	1	[{"added": {}}]	10	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	Gimnasio	clase
8	Gimnasio	plan
9	Gimnasio	socio
10	Gimnasio	inscripcion
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	Gimnasio	0001_initial	2026-09-21 15:53:53.799274-03
2	contenttypes	0001_initial	2026-09-21 15:53:53.806018-03
3	auth	0001_initial	2026-09-21 15:53:53.855529-03
4	admin	0001_initial	2026-09-21 15:53:53.871173-03
5	admin	0002_logentry_remove_auto_add	2026-09-21 15:53:53.876388-03
6	admin	0003_logentry_add_action_flag_choices	2026-09-21 15:53:53.881372-03
7	contenttypes	0002_remove_content_type_name	2026-09-21 15:53:53.892358-03
8	auth	0002_alter_permission_name_max_length	2026-09-21 15:53:53.89736-03
9	auth	0003_alter_user_email_max_length	2026-09-21 15:53:53.904575-03
10	auth	0004_alter_user_username_opts	2026-09-21 15:53:53.908551-03
11	auth	0005_alter_user_last_login_null	2026-09-21 15:53:53.913126-03
12	auth	0006_require_contenttypes_0002	2026-09-21 15:53:53.914096-03
13	auth	0007_alter_validators_add_error_messages	2026-09-21 15:53:53.918095-03
14	auth	0008_alter_user_username_max_length	2026-09-21 15:53:53.925717-03
15	auth	0009_alter_user_last_name_max_length	2026-09-21 15:53:53.931253-03
16	auth	0010_alter_group_name_max_length	2026-09-21 15:53:53.937301-03
17	auth	0011_update_proxy_permissions	2026-09-21 15:53:53.941773-03
18	auth	0012_alter_user_first_name_max_length	2026-09-21 15:53:53.946779-03
19	sessions	0001_initial	2026-09-21 15:53:53.95346-03
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
hh1jedclahib0clot5682ncbftot4qfx	.eJxVjDsOwjAQBe_iGln-LfZS0ucM1jprkwCypTipEHeHSCmgfTPzXiLStk5x63mJM4uLMOL0uyUaH7nugO9Ub02Ora7LnOSuyIN2OTTOz-vh_h1M1KdvPVp2BT0q4yBY8N5pT0Qug2HNKgNh0oEIoRgGxcAWlQ5c4FycQRTvD8zdN1E:1x8kW5:IUIjArlC_VeLvuFeQKkStNSWkX2CZYtUcrKG5m97tDg	2026-10-05 17:21:33.422104-03
g1khwzrcxvqxr4wamv3uis4r0q6fw375	eyJjbGllbnRlX3NvY2lvX2lkIjo2LCJjbGllbnRlX25vbWJyZSI6Ikp1YW4gUFx1MDBlOXJleiJ9:1x8kW5:s2Li35pZFmt2q2HpVv0EhT_Ykd9qjjH9odHwlaXkw28	2026-10-05 17:21:33.467307-03
kykfw42lmb57a80dl8jcoxssd0jbfu7r	.eJxVjDsOwjAQBe_iGln-LfZS0ucM1jprkwCypTipEHeHSCmgfTPzXiLStk5x63mJM4uLMOL0uyUaH7nugO9Ub02Ora7LnOSuyIN2OTTOz-vh_h1M1KdvPVp2BT0q4yBY8N5pT0Qug2HNKgNh0oEIoRgGxcAWlQ5c4FycQRTvD8zdN1E:1x8kqU:NApchth1-nf08T___tWnXtaIftMqK-LDvbeTl0OFzJ0	2026-10-05 17:42:38.467572-03
l09vclm91qlt3nw64339rp6apqrgvo24	.eJxVjDsOwjAQBe_iGln-LfZS0ucM1jprkwCypTipEHeHSCmgfTPzXiLStk5x63mJM4uLMOL0uyUaH7nugO9Ub02Ora7LnOSuyIN2OTTOz-vh_h1M1KdvPVp2BT0q4yBY8N5pT0Qug2HNKgNh0oEIoRgGxcAWlQ5c4FycQRTvD8zdN1E:1x8l0k:NdanRmFpb0hfxaSswnm-VTchqr8E929_rIJak54ZkvE	2026-10-05 17:53:14.470625-03
\.


--
-- Name: Gimnasio_clase_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Gimnasio_clase_id_seq"', 3, true);


--
-- Name: Gimnasio_inscripcion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Gimnasio_inscripcion_id_seq"', 68, true);


--
-- Name: Gimnasio_plan_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Gimnasio_plan_id_seq"', 6, true);


--
-- Name: Gimnasio_socio_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Gimnasio_socio_id_seq"', 71, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 40, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 2, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 3, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 10, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 19, true);


--
-- Name: Gimnasio_clase Gimnasio_clase_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Gimnasio_clase"
    ADD CONSTRAINT "Gimnasio_clase_pkey" PRIMARY KEY (id);


--
-- Name: Gimnasio_inscripcion Gimnasio_inscripcion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Gimnasio_inscripcion"
    ADD CONSTRAINT "Gimnasio_inscripcion_pkey" PRIMARY KEY (id);


--
-- Name: Gimnasio_plan Gimnasio_plan_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Gimnasio_plan"
    ADD CONSTRAINT "Gimnasio_plan_pkey" PRIMARY KEY (id);


--
-- Name: Gimnasio_socio Gimnasio_socio_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Gimnasio_socio"
    ADD CONSTRAINT "Gimnasio_socio_pkey" PRIMARY KEY (id);


--
-- Name: Gimnasio_socio Gimnasio_socio_rut_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Gimnasio_socio"
    ADD CONSTRAINT "Gimnasio_socio_rut_key" UNIQUE (rut);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: Gimnasio_inscripcion_clase_id_d28abbee; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Gimnasio_inscripcion_clase_id_d28abbee" ON public."Gimnasio_inscripcion" USING btree (clase_id);


--
-- Name: Gimnasio_inscripcion_socio_id_b9317ac2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Gimnasio_inscripcion_socio_id_b9317ac2" ON public."Gimnasio_inscripcion" USING btree (socio_id);


--
-- Name: Gimnasio_socio_plan_id_e0418368; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Gimnasio_socio_plan_id_e0418368" ON public."Gimnasio_socio" USING btree (plan_id);


--
-- Name: Gimnasio_socio_rut_12870889_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Gimnasio_socio_rut_12870889_like" ON public."Gimnasio_socio" USING btree (rut varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: Gimnasio_inscripcion Gimnasio_inscripcion_clase_id_d28abbee_fk_Gimnasio_clase_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Gimnasio_inscripcion"
    ADD CONSTRAINT "Gimnasio_inscripcion_clase_id_d28abbee_fk_Gimnasio_clase_id" FOREIGN KEY (clase_id) REFERENCES public."Gimnasio_clase"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Gimnasio_inscripcion Gimnasio_inscripcion_socio_id_b9317ac2_fk_Gimnasio_socio_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Gimnasio_inscripcion"
    ADD CONSTRAINT "Gimnasio_inscripcion_socio_id_b9317ac2_fk_Gimnasio_socio_id" FOREIGN KEY (socio_id) REFERENCES public."Gimnasio_socio"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: Gimnasio_socio Gimnasio_socio_plan_id_e0418368_fk_Gimnasio_plan_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Gimnasio_socio"
    ADD CONSTRAINT "Gimnasio_socio_plan_id_e0418368_fk_Gimnasio_plan_id" FOREIGN KEY (plan_id) REFERENCES public."Gimnasio_plan"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict DOhknbYAOA6idNE1E6BlbgSfrHlS3PQLSSMQy2uphIu419GoaGVbo52fxfoHTXz

